### ISSUE TITLE
Timeout on DPlay API

### ISSUE THREAD

**Issue by Jean85** [NeverWise/plugin.video.dplay#1]
Since yesterday, the DPlay API fails to load the list of available shows. It seems related to the fact that this app tries to retrieve the list all at once, but the API on the site is used in a paginated way, 50 items at a time.

Can we refactor the code to do the same? Unfortunately I'm no Python coder, or I would do it myself...

**Comment by gex77** [comment]
thanks to your tip about requesting 50 items per page I've been able to fix the problem.

Given that it's my very first attempt with Python I hope it's a decent work.
It seems to works pretty well on both my PC and NAS

#3

**Comment by Jean85** [comment]
Thanks! I will be trying that ASAP on my RPi; I closed my PR since it was not complete as yours.

**Comment by Mrdanto** [comment]
Sorry but as a totally inexpert I did not understand how to fix the issue my own.
1 - will the fixed add-on disposable on official repos of Kodi?
2 - which file have I to change ed where is it?
Thanks...

**Comment by Jean85** [comment]
To have the plugin updated in the offical repos, we need the intervention of the mantainer.
To fix it manually, you should copy the content of the modified file (as in #3 ) into your Kodi plugin folder...

**Comment by Mrdanto** [comment]
I have to overwrite previous file haven't I?

**Comment by Jean85** [comment]
Exactly; you can always reinstall the addon if you ruin anything.

**Comment by old-starax** [comment]
Great job jean85, thanks!

**Comment by Mrdanto** [comment]
Ti scrivo in italiano, tanto mi sembra che siamo connazionali e scusami 
per il disturbo.

Quale è il file che devo modificare e dove lo trovo?

Devo cancellare tutto il contenuto e sostituirlo con #3 
https://github.com/NeverWise/plugin.video.dplay/pull/3 oppure devo 
cambiare solo una parte di esso?

Il 24/10/2016 10:22, Alessandro Lai ha scritto:

**Comment by gex77** [comment]
download this file
https://github.com/gex77/plugin.video.dplay/archive/master.zip
and save it as plugin.video.dplay-master.zip

then go to Kodi and install addon from "settings" > "add-ons" > "install from zip file"

---

scaricati questo file
https://github.com/gex77/plugin.video.dplay/archive/master.zip
e salvalo come "plugin.video.dplay-master.zip"

apri Kodi e installalo da "impostazioni" > "add-on" > "installa da un file zip"

**Comment by Mrdanto** [comment]
Grazie infinite ho risolto. Sei stato davvero gentile.
Penserò a te ogni volta che guarderò cucine da incubo su dplay.
Buona serata...
Il giorno 25/ott/2016 20:22, "gex77" notifications@github.com ha scritto:

**Comment by LukSlackwalker** [comment]
Hi everyone,
this is my first post on GitHub so be patient.
I solved the timeout issue modifying the file default.py on this line:
Old: 
`shows = Util.getResponseJson('http://it.dplay.com/api/v2/ajax/modules?items=1000&page_id=32&module_id=26')`

New:
 `shows = Util.getResponseJson('http://it.dplay.com/api/v2/ajax/modules?page_id=32&module_id=26&items=500')
`

Hope this help.
Greetings.
Luk
