### ISSUE TITLE
errore aprendo i video su android e kodi 16.1

### ISSUE THREAD

**Issue by peppesr** [NeverWise/plugin.video.dplay#11]
cercando di aprire i video con kodi 16.1 su android viene mostrato un errore. ti allego due immagini credo che la parte del log visualizzata sia sufficiente se così non fosse provo a caricare tutto il log.
![01](https://cloud.githubusercontent.com/assets/1901507/25970453/01d74ea2-3699-11e7-9c3e-a185ef26d59c.jpg)

![02](https://cloud.githubusercontent.com/assets/1901507/25970462/0a279152-3699-11e7-94ac-d8597747d22b.jpg)

su kodi 17.1 windows nessun problema
Grazie
Peppe

**Comment by lastway** [comment]
Anche io ho problemi con il nuovo plugin e Kodi 16.1 su piattaforma Win7 / 10. Nessun problema invece con Kodi 17.1. Soluzioni? Di seguito riporto il log relativo a Kodi 16.1.

00:47:50 T:42764   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: astimezone() argument 1 must be datetime.tzinfo, not None
                                            Traceback (most recent call last):
                                              File "C:\Users\Utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 170, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\Utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 37, in __init__
                                                vd = self._getVideoInfo(video)
                                              File "C:\Users\Utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 154, in _getVideoInfo
                                                date = date.astimezone(nw.gettzlocal())
                                            TypeError: astimezone() argument 1 must be datetime.tzinfo, not None
                                            -->End of Python script error report<--
00:47:50 T:43596   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/?action=s&at=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXlpdDo1MTY1MDc0YS0yNzZmLTQzMTctOTA2Yi00MzFiOTI0YTBiNjIiLCJqdGkiOiJ0b2tlbi0zMjRjOGNkMC05NzIxLTQxYzQtOGQwNi0yYjYxNzc3Yjk5NDQiLCJhbm9ueW1vdXMiOnRydWUsImlhdCI6MTQ5NDU0Mjg3NX0%3d.lw8U4oTYeKsQLKGL4294FNdCqoCZ0waixwFPoH4M7iI%3d__!__w6ggjAfuphfOG6%2fATvhU7QhGfdWCt5qU5PoQRQgZtyA%3d&value=51
00:47:50 T:43596   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/?action=s&at=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXlpdDo1MTY1MDc0YS0yNzZmLTQzMTctOTA2Yi00MzFiOTI0YTBiNjIiLCJqdGkiOiJ0b2tlbi0zMjRjOGNkMC05NzIxLTQxYzQtOGQwNi0yYjYxNzc3Yjk5NDQiLCJhbm9ueW1vdXMiOnRydWUsImlhdCI6MTQ5NDU0Mjg3NX0%3d.lw8U4oTYeKsQLKGL4294FNdCqoCZ0waixwFPoH4M7iI%3d__!__w6ggjAfuphfOG6%2fATvhU7QhGfdWCt5qU5PoQRQgZtyA%3d&value=51) failed

Saluti e grazie!

**Comment by NeverWise** [comment]
Dovrei aver risolto.
Era un bug nella libreria script.module.neverwise.
Aggiornando quest'ultima si dovrebbe sistemare.
Per chi usa il repository dovrebbe andare a posto da sola.

**Comment by nx-99** [comment]
Grazie NeverWise, ho aggiornato script.module.neverwise tramite i tuoi repo, ora funziona tutto, su kodi 16.1 di kubuntu 16.04.2 lts. ciao.

**Comment by lastway** [comment]
Grazie NeverWise!
Problema risolto! Anche se ho notato che purtroppo ora gli episodi non vengono più raggruppati per stagione...  Potrebbe essere un'implementazione futura?

**Comment by NeverWise** [comment]
Si, tempo permettendo potrebbe essere sviluppata.

**Comment by luX0r-reload** [comment]
Ciao, non so se dipende dall'ultimo aggiornamento della libreria script.module.neverwise, ma fino a qualche giorno fa andava tutto alla perfezione (Kodi 17.1 su LibreElec) ma oggi c'è qualche problemino.
L'elenco degli show e degli episodi è ok, ma quando si va in play su uno degli episodi va in errore.

**Comment by lastway** [comment]
Con la correzione apportata il plugin ha funzionato per qualche giorno, ma poi di nuovo l'errore di sempre "Errore connessione internet" che si presenta non appena viene fatto partire l'episodio desiderato. Questo su piattaforma Windows e, sentendo altre persone, su Android.
Non escludo siano cambiate nuovamente le API o altro...

**Comment by nx-99** [comment]
Già pure qui con  kodi 16.1 di kubuntu 16.04.2 lts 
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "/home/seawolf/.kodi/addons/plugin.video.dplay-master-Version-1.0.3/default.py", line 170, in <module>
                                                dplay = Dplay()
                                              File "/home/seawolf/.kodi/addons/plugin.video.dplay-master-Version-1.0.3/default.py", line 49, in __init__
                                                result = self._getStream(self._params['value'])
                                              File "/home/seawolf/.kodi/addons/plugin.video.dplay-master-Version-1.0.3/default.py", line 75, in _getStream
                                                response = self._getResponseJson('https://dplay-south-prod.disco-api.com/playback/videoPlaybackInfo/{0}'.format(video_id), True)
                                              File "/home/seawolf/.kodi/addons/plugin.video.dplay-master-Version-1.0.3/default.py", line 123, in _getResponseJson
                                                if 'Data' in response.body:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
07:58:14 T:139964534561152   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
`

**Comment by luX0r-reload** [comment]
Confermo anche su Linux (Fedora e LibreElec).
Considerato che il problema è multi piattaforma, credo anche io che ci sia stato un aggiornamento alle API.

**Comment by NeverWise** [comment]
Ho rilasciato una nuova versione con il fix.
Ora dovrebbe funzionare.

**Comment by nx-99** [comment]
Grande  NeverWise, ora funzia.
Grazie.

**Comment by lastway** [comment]
Che dire NeverWise... Grazie mille!! Ora è a posto!
