### ISSUE TITLE
Il plugin non funziona piu'

### ISSUE THREAD

**Issue by someuser94** [NeverWise/plugin.video.dplay#13]
Sul sito dplay hanno aggiornato il metodo di pubblicazione del file video e i file m3u8 non sono piu' compatibili col plugin. I nuovi file pubblicati hanno un url diverso per l'audio e il video

**Comment by NeverWise** [comment]
Grazie all'aiuto di alcuni utenti ho rilasciato la versione 1.0.5. Prova ad installarla e fammi sapere se ora è tutto ok.
