### ISSUE TITLE
Plugin doesn't work all times

### ISSUE THREAD

**Issue by andremanz8** [NeverWise/plugin.video.dplay#16]
Hello, I tried to use Dplay plugin, but it often fail to open.
Sometime it works if I try to clear the cache and I reinstall it many times, but maybe that the next day, without touch anything, it doesn't work again.
Sometimes I was able to make it work again with the reinstallation, but in the last few days there's nothing I can do.
I use the last release on your repository. This is my log, tried it both on windows and on raspberry

`11:29:22.107 T:5112   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:29:36.139 T:2964   ERROR: Previous line repeats 9 times.
11:29:36.139 T:2964   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 174, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 24, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:29:36.172 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:29:36.174 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
11:32:56.305 T:3108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 174, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 24, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:32:56.324 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:32:56.325 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
11:33:49.569 T:2880   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
11:33:51.655 T:2752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 179, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 25, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:33:51.672 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:33:51.672 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
11:36:18.965 T:2880   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
11:36:21.946 T:2004   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 179, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 25, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:36:22.012 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:36:22.012 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
11:36:31.393 T:1216   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:37:43.742 T:5972   ERROR: Previous line repeats 2 times.
11:37:43.742 T:5972   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 179, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 25, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:37:43.799 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:37:43.801 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
11:37:48.046 T:4192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 179, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\utente\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 25, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
11:37:48.097 T:2880   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dplay/
11:37:48.098 T:2880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
`

**Comment by NeverWise** [comment]
Thanks to the help of some users I have released version 1.0.5. Try to install it and let me know if everything is ok now.
