### ISSUE TITLE
Plugin Error on load

### ISSUE THREAD

**Issue by fabiocasciano** [NeverWise/plugin.video.dplay#17]
Dear Dev,
as I start plugin i get this error. I'm with RPi3 with OSMC latest stable version.
18:42:15.693 T:1682699008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Description',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dplay/default.py", line 174, in <module>
                                                dplay = Dplay()
                                              File "/home/osmc/.kodi/addons/plugin.video.dplay/default.py", line 24, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Ima$
                                            KeyError: ('Description',)
                                            -->End of Python script error report<--
18:42:15.807 T:1925818880   ERROR: GetDirectory - Error getting plugin://plugin.video.dplay/
18:42:15.808 T:1925818880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed

**Comment by Acromion1754** [comment]
Hi Dev, same error here. Kodi 18 with LibreElec Alpha 8.90.007 
complete log: http://paste.kodi.tv/uyoqesubeg

  ERROR: Control 50 in window 10025 has been asked to focus, but it can't
  ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'Description'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dplay/default.py", line 179, in <module>
                                                dplay = Dplay()
                                              File "/storage/.kodi/addons/plugin.video.dplay/default.py", line 25, in __init__
                                                self._addItem(show['Name'], { 'at' : self._access_token, 'action' : 's', 'value' : show['Id'] }, show['Images'][0]['Src'], fanart, show['Description'])
                                            KeyError: 'Description'
                                            -->End of Python script error report<--
  ERROR: GetDirectory - Error getting plugin://plugin.video.dplay/
  ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed
  ERROR: GetDirectory - Error getting
 ERROR: Previous line repeats 2 times.
 NOTICE: Samba is idle. Closing the remaining connections

**Comment by NeverWise** [comment]
Thanks to the help of some users I have released version 1.0.5. Try to install it and let me know if everything is ok now.
