### ISSUE TITLE
lista episodi vuota

### ISSUE THREAD

**Issue by nocelab** [NeverWise/plugin.video.dplay#20]
ciao... sto provando il plugin (1.0.5 con kodi pc and raspberry) e la lista del programma "Nudi e Crudi XL" appare vuota

**Comment by NeverWise** [comment]
Ciao,
la lista appare vuota perchè per alcuni episodi (nel tuo caso tutta la serie) è necessario la registrazione al sito dplay.
Funzionalità che per ora non è gestita dall'addon.

**Comment by nocelab** [comment]
è chiaro... l'app Android li mostra anche senza account, pensavo funzionasse allo stesso modo

**Comment by NeverWise** [comment]
Non so come funziona l'app android, ma in teoria anche da android se non sei registrato a dplay (o facebook) non dovrebbe farti riprodurre il video.
