### ISSUE TITLE
Errore connessione internet

### ISSUE THREAD

**Issue by Gythion** [NeverWise/plugin.video.dplay#21]
Scusate, ma dà di nuovo: "Errore connessione internet".

**Comment by NeverWise** [comment]
Hai installato l'ultima versione? Ti consiglio quella che è nel mio repository a questo indirizzo: https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip

**Comment by Gythion** [comment]
Sì, beh, in realtà l'avevo scaricata sempre da qui ed, ovviamente, è quella della repo. Cmq, grazie.

**Comment by andremanz8** [comment]
Da ieri ha ricominciato a presentarsi l'"errore connessione internet".
cosa curiosa: non avviene su tutte le serie, ma solo su alcune, e cosa ancora più curiosa, un filmato che 2 giorni fa ho visto senza alcun problema, da ieri invece ho questo errore.
C'è un motivo in questo comportamento?
Premetto che ho usato il plugin della repo di neverwise (versione plugin dplay 1.0.6)

**Comment by NeverWise** [comment]
Quell'errore compare anche in caso di programmi a pagamento.
Dovresti verificare se quella puntata che dici tu non sia ora a pagamento oppure dirmi di che contenuto si tratta che controllo.

**Comment by andremanz8** [comment]
hai perfettamente ragione, non avevo notato che quelle puntate fossero contrassegnate come plus, cosa curiosa è che la puntata 9 che ho guardato 2 giorni fa evidentemente non lo fosse, mentre ora lo è...
se non altro ora ho una spiegazione...
https://it.dplay.com/utente/autenticazione/?redirect&channel=realtime&show=5-gemelle-sotto-un-tetto&video=stagione-4-episodio-9-domande&state=premium#login
