### ISSUE TITLE
OSMC Ultimate stable - Errore Connessione Internet

### ISSUE THREAD

**Issue by DjDiabolik** [NeverWise/plugin.video.dplay#5]
Come indicato nel titolo............ Disinstallando la 1.0 vecchia versione presente nel repository ufficiale del kodi ed eliminata la sua cartella con le vecchie configurazioni ed installata questa 1.0.1 scaricando lo zip dei source.
L'installazione va a buon fine......... si riesce a fare tutte le configurazioni del caso ma quando lo avvi si può vedere lo spin in basso a destra per una 60ina di secondi poi non succede niente e a schermo compare un'errore che dice proprio "Errore Connessione Internet" ed è ovvio che il mio Raspberry Pi2 è correttamente connesso ad internet............

**Comment by NeverWise** [comment]
A me funziona correttamente quindi credo che il problema sia il numero di spettacoli che vengono recuperati ad ogni richiesta. Il valore predefinito è 500 (un po' alto effettivamente) ma dalle impostazioni dell'addon (o plugin se preferisci) è possibile abbassarlo a 50. Con questa modifica dovrebbe funzionare.

**Comment by DjDiabolik** [comment]
Confermo in toto................infatti ho messo 50 e dopo pochi istanti tutti (a dire il vero quei pochi che vengono caricati e sembra nemmeno senza un criterio... ovviamente sarebbe da criticare chi gestisce il sito cosi male....) i vari show sono comparsi a schermo.
