### ISSUE TITLE
Master 1.0.2 non si installa per problema dipendenza

### ISSUE THREAD

**Issue by erujp** [NeverWise/plugin.video.dplay#6]
Salve, l'ultima versione non mi si installa (su due sistemi diversi) dandomi questo errore:
"La dipendenza da script.module.neverwise versione 1.0.8 non può essere trovata."
La versione 1.0.0 da repository ufficiale (o la 1.0.0 con il file .py modificato che si trova in giro) invece si installa.

Kodi 16.1 su uno Xtreamer Wonder Pro con OpenElec 6.95.2 7.0, ma anche Kodi 17 su Mac OSX 10.11.6.

**Comment by NeverWise** [comment]
Si, se vuoi fare tutto "a mano" devi prima installare una libreria che puoi scaricare da qui: https://github.com/NeverWise/script.module.neverwise/archive/master.zip

Il mio consiglio però è di installare il repository che puoi scaricare da qui: https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip.
Si installa come un normale addon, gestisce automaticamente le dipendenze e, se l'impostazione di kodi è attiva, aggiorna gli addon installati automaticamente.

**Comment by erujp** [comment]
Grazie, ho installato la repository e ora funziona tutto. MA ho voluto installare e provare anche l'addon per la TV live, e ora ho problemi con quello (non funziona). C'è un forum o un posto dove si può parlare di quello?

**Comment by NeverWise** [comment]
No, non c'è perchè è un servizio che avevo fatto più che altro per me ma non è un problema se lo vuoi usare è che è un po' complesso.
In poche parole è un servizio che si preoccupa di tenere la guida tv e alcuni canali tv aggiornati per il [client PVR](http://kodi.wiki/view/PVR) [IPTV Simple Client](http://kodi.wiki/view/Add-on:IPTV_Simple_Client).
Quindi non è un vero e proprio addon funzionante, ci sono solo due funzioni nelle impostazioni dell'addon.

**Comment by erujp** [comment]
Ho capito. Grazie di tutto!
