### ISSUE TITLE
Installation problem on fresh install

### ISSUE THREAD

**Issue by luX0r-reload** [NeverWise/plugin.video.dplay#7]
Hi, version 1.02 doesn't install on fresh Kodi installation.
Try it on Android with Kodi 16.1, on OpenELEC/LibreELEC with Kodi 16.0 and Kodi 16.1, and on my Linux workstation with Kodi Krypton. On all platforms it returns the same error:
"The dependency on script.module.neverwise version 1.0.8 not loaded/installed".

p.s. oops ho scritto in inglese ma forse sarebbe stato meglio in italiano :)

**Comment by luX0r-reload** [comment]
Ho risolto installando manualmente la versione 1.0.8 della dipendenza script.module.neverwise.
Ma perché nelle versioni precedenti non ho mai installato lo script.module.neverwise?

**Comment by NeverWise** [comment]
Essendo una dipendenza si è installato automaticamente quando hai installato DPlay dal repository di kodi.
Per il futuro ti consiglio di installare il mio repository per evitare di fare tutte queste operazioni a mano che a mio avviso sono scomode.
L'indirizzo da cui scaricare il mio repository è questo: https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip

**Comment by Mrdanto** [comment]
La versione 1.0.2 non va di nuovo. Ha funzionato per un po' ma poi ricompare "Errore di connessione". Mi aiutate a risolvere? Grazie!!

**Comment by NeverWise** [comment]
Grazie all'aiuto di alcuni utenti ho rilasciato la versione 1.0.5. La dipendenza di script.module.neverwise è la 1.1.0 quindi devi installare anche quella se "fai tutto a mano". Altrimenti un metodo più semplice è quello di installare l'addon dal mio [repository](https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip).
