### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Mrdanto** [NeverWise/plugin.video.dplay#9]
The add-on has not worked since 15th of March. It seems the issue solved appeared again.
Could someone fix it again?

**Comment by Mrdanto** [comment]
Nessuno mi sa aiutare? :(

**Comment by nx-99** [comment]
Hanno modificato il sito dplay, blindando tutto.

**Comment by Mrdanto** [comment]
E non c'è soluzione?

**Comment by nx-99** [comment]
Aspettiamo NeverWise, se ha voglia e tempo di sistemarlo. Io per il momento sono riuscito a scaricarmi i video con uno script Greasemonkey (DPlay Download Script) per Firefox e li guardo offline. https://greasyfork.org/it/scripts/11108-dplay-download-script

**Comment by Gitner** [comment]
Usando DPlay Download, citato da nx-99, si può copiare il link che lo script estrae ed inserirlo in un file di testo con estensione .strm da dare in pasto a kodi. In questo modo è possibile continuare a guardare i contenuti in streaming senza attendere il completamento del download.
Un ringraziamento sentito a tutti quelli che portano avanti progetti come questo.
Grazie NewerWise e gex77
![schermata 2017-03-29 alle 12 06 35](https://cloud.githubusercontent.com/assets/25614611/24449792/c0ab72e2-1478-11e7-8a20-cdbeec1ee840.png)
![schermata 2017-03-29 alle 12 09 59](https://cloud.githubusercontent.com/assets/25614611/24449853/ed02ead2-1478-11e7-9cd9-0e8de8d89607.png)

**Comment by MaxChinni** [comment]
Anche con l'ultima versione di `youtube-dl` è possibile scaricare direttamente i video dal sito:
```
$ youtube-dl --version
2017.03.26
$ youtube-dl http://it.dplay.com/nove/fratelli-di-crozza/stagione-1-episodio-4/
[DPlayIt] stagione-1-episodio-4: Downloading webpage
[DPlayIt] stagione-1-episodio-4: Downloading JSON metadata
[DPlayIt] stagione-1-episodio-4: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 460
[download] Destination: Fratelli di Crozza - Episodio 4-7845.mp4
[download] 100% of 1.61GiB in 06:49
[ffmpeg] Fixing malformated aac bitstream in "Fratelli di Crozza - Episodio 4-7845.mp4"

```

**Comment by nx-99** [comment]
Cavolo, con youtube-dl dei repo di ubuntu non funziona, ora ho aggiornato youtube-dl come indicato qui https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl
Bene meglio avere più opzioni per vedermi  Affari a quattro ruote :)

**Comment by NeverWise** [comment]
Colgo l'occasione per ringraziarvi: sia per i complimenti che per le soluzioni alternative che postate, che sono utili spunti per possibili implementazioni, e per dirvi che spero presto di rilasciare una versione funzionante dell'addon.
Purtroppo ho poco tempo. Scusate. :-(

**Comment by antok602** [comment]
ho trovato un sistema più veloce per vedere in streaming da dplay, andate su pasty.link e inserite l url del sito ad esempio http://it.dplay.com/focus/antichi-misteri/stagione-2-episodio-11-il-diluvio-universale/  .
Copiate il risultato su jdownloader e lo scaricate alla qualità che volete, e in streaming con vlc

**Comment by pandvan** [comment]
In ambiente linux uso l'ottimo [Streamlink](https://github.com/streamlink/streamlink) dopo aver estrapolato il link del flusso principale HLS.
